import React from 'react'
import { motion,useScroll } from 'motion/react'

const Scroll = () => {

    const  scrollYProgree = useScroll().scrollYProgress

    return (
        <div id='con'>
            <motion.div
             style={{
                scaleX:scrollYProgree
             }}
            id='line'></motion.div>
            <h1 id='h1'>Lorem ipsum dolor sit</h1>
            <p id='para'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea eaque quis tempora tenetur perspiciatis natus minima temporibus illo aut asperiores. Quis similique quos eum animi dignissimos. Corporis rem at incidunt excepturi nostrum non quos omnis, veniam, rerum repellat sunt repellendus nesciunt quidem tempore id, itaque commodi voluptas officiis necessitatibus sapiente. Dolore voluptatibus voluptate commodi ut illum! Consequatur consectetur, eius sed maxime fugit cumque delectus dolorem expedita, veritatis minus voluptatum voluptatem sequi ex accusamus mollitia? Totam temporibus vero saepe error et debitis atque voluptatem doloribus ipsum. Enim corrupti maxime, temporibus sapiente consequuntur nemo laborum eveniet repellendus cumque, provident obcaecati in blanditiis. Facilis, et itaque earum temporibus fugit cupiditate ab vero libero aliquam vitae consequuntur quaerat maxime sint eligendi tempore ratione quibusdam facere animi quos qui similique, fugiat pariatur! Obcaecati nulla esse harum accusamus quis dolorem assumenda vitae fugit atque nobis cumque exercitationem expedita consequuntur sapiente ex quod deleniti, culpa architecto officiis laborum! Dolore rem unde officiis incidunt? Nobis unde qui nihil amet officiis culpa ut ad? Provident ratione quidem aspernatur maiores magnam? Magni, neque tempore molestiae quaerat quisquam esse quo, sit accusamus, perferendis porro dignissimos consequatur error omnis doloremque maiores odit soluta ducimus cumque. Accusamus ab molestias corrupti at natus nam distinctio iure doloremque beatae quam iusto dicta obcaecati atque ducimus deserunt maiores, dolorem praesentium necessitatbr <br /> <br />
            ibus? Neque excepturi expedita odit consequatur minima, ea sunt perspiciatis nam consectetur tempore mollitia nisi cum similique reprehenderit maxime ut blanditiis eius id atque laboriosam qui. Dolor eveniet commodi praesentium debitis perspiciatis ex voluptatibus, dicta doloremque placeat illo voluptates optio tempora culpa, quisquam id obcaecati saepe sint error. Labore veniam similique eveniet officia ea. Quae maxime accusantium cum ipsa provident aliquid, ipsum perspiciatis harum qui, optio eveniet sit odit. Odio eos distinctio nisi, nemo praesentium mollitia nulla omnis minima suscipit amet neque quod minus libero expedita dolorum! Placeat rem a iusto voluptatem vel aperiam facere ratione, repellendus neque molestiae id rerum eaque repellat inventore officia nulla eius sapiente dolorum veniam. Eius fuga sint eum illum cum harum temporibus, natus, illo itaque libero sapiente commodi atque aliquid ullam inventore tempora perferendis assumenda animi tempore quam vitae dignissimos! In iure laboriosam porro inventore explicabo cumque ipsam nisi, ad sint, corporis itaque iusto illum deserunt? <br /> <br />Debitis amet sed soluta neque quam beatae modi harum, expedita, fugit ut quibusdam culpa maxime! Totam dolorem iste suscipit dignissimos quia nam aspernatur blanditiis odit numquam amet assumenda est sint, provident cumque incidunt debitis nemo cupiditate tempore recusandae asperiores qui eveniet quas illum molestias? Culpa tempora officiis esse laborum eveniet repellendus cumque, provident obcaecati in blanditiis. Facilis, et itaque earum temporibus fugit cupiditate ab vero libero aliquam vitae consequuntur quaerat maxime sint eligendi tempore ratione quibusdam facere animi quos qui similique, fugiat pariatur! Obcaecati nulla esse harum accusamus quis dolorem assumenda vitae fugit atque nobis cumque exercitationem expedita consequuntur sapiente ex quod deleniti, culpa architecto officiis laborum! Dolore rem unde officiis incidunt? Nobis unde qui nihil amet officiis culpa ut ad? Provident ratione quidem rerum praesentium adipisci sint totam est vitae rem? Provident, voluptas necessitatibus! Dolores qui, illo quo quas id et! Veniam, laborum! Aut quisquam quas debitis corrupti suscipit nihil sed distinctio eligendi expedita molestias, error, reprehenderit vitae totam earum enim ipsam blanditiis temporibus recusandae adipisci vero quis quos! Facere quo, doloremque molestiae enim quia dolorum. Libero distinctio rerum quas, officia eveniet fugit provident odit autem itaque vitae dolore similique aliquid sed <br /> <br />iusto aliquam inventore impedit facere illo maxime deserunt sunt in amet ea doloremque! Voluptate, culpa sapiente?</p>
            <p id='para'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea eaque quis tempora tenetur perspiciatis natus minima temporibus illo aut asperiores. Quis similique quos eum animi dignissimos. Corporis rem at incidunt excepturi nostrum non quos omnis, veniam, rerum repellat sunt repellendus nesciunt quidem tempore id, itaque commodi voluptas officiis necessitatibus sapiente. Dolore voluptatibus voluptate commodi ut illum! Consequatur consectetur, eius sed maxime fugit cumque delectus dolorem expedita, veritatis minus voluptatum voluptatem sequi ex accusamus mollitia? Totam temporibus vero saepe error et debitis atque voluptatem doloribus ipsum. Enim corrupti maxime, temporibus sapiente consequuntur nemo laborum eveniet repellendus cumque, provident obcaecati in blanditiis. Facilis, et itaque earum temporibus fugit cupiditate ab vero libero aliquam vitae consequuntur quaerat maxime sint eligendi tempore ratione quibusdam facere animi quos qui similique, fugiat pariatur! Obcaecati nulla esse harum accusamus quis dolorem assumenda vitae fugit atque nobis cumque exercitationem expedita consequuntur sapiente ex quod deleniti, culpa architecto officiis laborum! Dolore rem unde officiis incidunt? Nobis unde qui nihil amet officiis culpa ut ad? Provident ratione quidem aspernatur maiores magnam? Magni, neque tempore molestiae quaerat quisquam esse quo, sit accusamus, perferendis porro dignissimos consequatur error omnis doloremque maiores odit soluta ducimus cumque. Accusamus ab molestias corrupti at natus nam distinctio iure doloremque beatae quam iusto dicta obcaecati atque ducimus deserunt maiores, dolorem praesentium necessitatbr <br /> <br />
            ibus? Neque excepturi expedita odit consequatur minima, ea sunt perspiciatis nam consectetur tempore mollitia nisi cum similique reprehenderit maxime ut blanditiis eius id atque laboriosam qui. Dolor eveniet commodi praesentium debitis perspiciatis ex voluptatibus, dicta doloremque placeat illo voluptates optio tempora culpa, quisquam id obcaecati saepe sint error. Labore veniam similique eveniet officia ea. Quae maxime accusantium cum ipsa provident aliquid, ipsum perspiciatis harum qui, optio eveniet sit odit. Odio eos distinctio nisi, nemo praesentium mollitia nulla omnis minima suscipit amet neque quod minus libero expedita dolorum! Placeat rem a iusto voluptatem vel aperiam facere ratione, repellendus neque molestiae id rerum eaque repellat inventore officia nulla eius sapiente dolorum veniam. Eius fuga sint eum illum cum harum temporibus, natus, illo itaque libero sapiente commodi atque aliquid ullam inventore tempora perferendis assumenda animi tempore quam vitae dignissimos! In iure laboriosam porro inventore explicabo cumque ipsam nisi, ad sint, corporis itaque iusto illum deserunt? <br /> <br />Debitis amet sed soluta neque quam beatae modi harum, expedita, fugit ut quibusdam culpa maxime! Totam dolorem iste suscipit dignissimos quia nam aspernatur blanditiis odit numquam amet assumenda est sint, provident cumque incidunt debitis nemo cupiditate tempore recusandae asperiores qui eveniet quas illum molestias? Culpa tempora officiis esse laborum eveniet repellendus cumque, provident obcaecati in blanditiis. Facilis, et itaque earum temporibus fugit cupiditate ab vero libero aliquam vitae consequuntur quaerat maxime sint eligendi tempore ratione quibusdam facere animi quos qui similique, fugiat pariatur! Obcaecati nulla esse harum accusamus quis dolorem assumenda vitae fugit atque nobis cumque exercitationem expedita consequuntur sapiente ex quod deleniti, culpa architecto officiis laborum! Dolore rem unde officiis incidunt? Nobis unde qui nihil amet officiis culpa ut ad? Provident ratione quidem rerum praesentium adipisci sint totam est vitae rem? Provident, voluptas necessitatibus! Dolores qui, illo quo quas id et! Veniam, laborum! Aut quisquam quas debitis corrupti suscipit nihil sed distinctio eligendi expedita molestias, error, reprehenderit vitae totam earum enim ipsam blanditiis temporibus recusandae adipisci vero quis quos! Facere quo, doloremque molestiae enim quia dolorum. Libero distinctio rerum quas, officia eveniet fugit provident odit autem itaque vitae dolore similique aliquid sed <br /> <br />iusto aliquam inventore impedit facere illo maxime deserunt sunt in amet ea doloremque! Voluptate, culpa sapiente?</p>
        </div>
    )
}

export default Scroll